# Generated by Django 3.1.4 on 2021-01-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TEST_Dokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
                ('zeit_erstellung', models.DateTimeField(auto_now_add=True)),
                ('mitarbeiter_id', models.IntegerField()),
            ],
        ),
    ]
