# Generated by Django 3.1.4 on 2020-12-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0002_auto_20201213_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow_Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.projekt')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow_Schema_Stufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.projekt')),
                ('prüffirma', models.ManyToManyField(to='superadmin.Firma')),
                ('vorstufe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projektadmin.workflow_schema_stufe')),
                ('workflow_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.workflow_schema')),
            ],
        ),
    ]
