# Generated by Django 3.1.4 on 2020-12-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0002_auto_20201214_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_schema_stufe',
            name='vorstufe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projektadmin.workflow_schema_stufe'),
        ),
    ]
