# Generated by Django 3.1.4 on 2020-12-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_auto_20201213_1406'),
        ('projektadmin', '0003_auto_20201214_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ordner_Firma_Freigabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freigabe_lesen', models.BooleanField()),
                ('freigabe_upload', models.BooleanField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.firma')),
                ('ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.projekt')),
            ],
        ),
        migrations.AddField(
            model_name='ordner',
            name='firma',
            field=models.ManyToManyField(through='projektadmin.Ordner_Firma_Freigabe', to='superadmin.Firma'),
        ),
        migrations.AddField(
            model_name='ordner',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.projekt'),
        ),
        migrations.AddField(
            model_name='ordner',
            name='überordner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner'),
        ),
    ]
