# Generated by Django 3.1.4 on 2020-12-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0004_auto_20201215_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordner',
            name='ist_root_ordner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordner',
            name='überordner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner'),
        ),
    ]
