# Generated by Django 3.1.4 on 2020-12-15 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0006_auto_20201215_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordner',
            name='workflow_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projektadmin.workflow_schema'),
        ),
    ]
