# Generated by Django 3.1.4 on 2020-12-28 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projektadmin', '0007_ordner_workflow_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFSch_Stufe_Mitarbeiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immer_erforderlich', models.BooleanField()),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wfsch_stufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.workflow_schema_stufe')),
            ],
        ),
        migrations.AddField(
            model_name='workflow_schema_stufe',
            name='mitarbeiter',
            field=models.ManyToManyField(through='projektadmin.WFSch_Stufe_Mitarbeiter', to=settings.AUTH_USER_MODEL),
        ),
    ]
