# Generated by Django 3.1.4 on 2021-01-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0008_auto_20201228_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_schema',
            name='projekt',
        ),
        migrations.CreateModel(
            name='WFSch_Stufe_Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_id', models.CharField(max_length=20)),
                ('workflow_schema_stufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.workflow_schema_stufe')),
            ],
        ),
    ]
