# Generated by Django 3.1.4 on 2021-01-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0009_auto_20210115_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_schema_stufe',
            name='projekt',
        ),
        migrations.RemoveField(
            model_name='workflow_schema_stufe',
            name='prüffirma',
        ),
    ]
