# Generated by Django 3.1.4 on 2021-01-15 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0010_auto_20210115_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_schema_stufe',
            name='vorstufe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projektadmin.workflow_schema_stufe'),
        ),
    ]
