# Generated by Django 3.1.4 on 2021-01-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0011_auto_20210115_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordner',
            name='projekt',
        ),
        migrations.RemoveField(
            model_name='ordner',
            name='überordner',
        ),
        migrations.AddField(
            model_name='ordner',
            name='unterordner',
            field=models.ManyToManyField(related_name='_ordner_unterordner_+', to='projektadmin.Ordner'),
        ),
    ]
