# Generated by Django 3.1.4 on 2021-01-19 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0012_auto_20210116_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Überordner_Unterordner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unterordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_unterordner', to='projektadmin.ordner')),
                ('überordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_überordner', to='projektadmin.ordner')),
            ],
        ),
    ]
