# Generated by Django 3.1.4 on 2021-01-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0013_überordner_unterordner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordner',
            name='unterordner',
        ),
    ]
