# Generated by Django 3.1.4 on 2021-01-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0014_remove_ordner_unterordner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordner',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='ordner_firma_freigabe',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='ordner_firma_freigabe',
            name='projekt',
        ),
        migrations.AddField(
            model_name='ordner_firma_freigabe',
            name='firma_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
