# Generated by Django 3.1.4 on 2021-01-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0015_auto_20210120_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordner_firma_freigabe',
            name='freigaben_erben',
            field=models.BooleanField(default=True),
        ),
    ]
