# Generated by Django 3.1.4 on 2021-01-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0016_ordner_firma_freigabe_freigaben_erben'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfsch_stufe_mitarbeiter',
            name='mitarbeiter',
        ),
        migrations.RemoveField(
            model_name='workflow_schema_stufe',
            name='mitarbeiter',
        ),
        migrations.AddField(
            model_name='wfsch_stufe_mitarbeiter',
            name='mitarbeiter_id',
            field=models.CharField(default='Das ist nicht gültig', max_length=20),
        ),
    ]
