# Generated by Django 3.1.4 on 2021-01-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0017_auto_20210121_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordner',
            name='unterordner',
            field=models.ManyToManyField(related_name='_ordner_unterordner_+', through='projektadmin.Überordner_Unterordner', to='projektadmin.Ordner'),
        ),
    ]
