# Generated by Django 3.1.4 on 2021-01-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0018_ordner_unterordner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_schema_stufe',
            name='bezeichnung',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
