# Generated by Django 3.1.4 on 2021-01-31 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0019_workflow_schema_stufe_bezeichnung'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfsch_stufe_mitarbeiter',
            name='gelöscht',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wfsch_stufe_mitarbeiter',
            name='zeitstempel',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 9, 32, 54, 826863, tzinfo=utc)),
        ),
    ]
