# Generated by Django 3.1.4 on 2021-01-31 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0020_auto_20210131_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfsch_stufe_mitarbeiter',
            name='zeitstempel',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
