# Generated by Django 3.1.4 on 2021-02-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0021_auto_20210131_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rolle_Gelöscht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelöscht', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.rolle')),
            ],
        ),
        migrations.CreateModel(
            name='Rolle_Bezeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.rolle')),
            ],
        ),
    ]
