# Generated by Django 3.1.4 on 2021-02-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0022_rolle_rolle_bezeichnung_rolle_gelöscht'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordner_Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner')),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.rolle')),
            ],
        ),
        migrations.CreateModel(
            name='Ordner_Rolle_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('ordner_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner_rolle')),
            ],
        ),
    ]
