# Generated by Django 3.1.4 on 2021-02-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0023_ordner_rolle_ordner_rolle_aktuell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordner_Freigabe_Lesen_Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freigabe_lesen', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('ordner_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner_rolle')),
            ],
        ),
    ]
