# Generated by Django 3.1.4 on 2021-02-02 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0025_ordner_freigabe_upload_rolle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordner_Rolle_Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_id', models.CharField(max_length=20)),
                ('ordner_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner_rolle')),
            ],
        ),
        migrations.CreateModel(
            name='Ordner_Rolle_Firma_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('ordner_rolle_firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner_rolle_firma')),
            ],
        ),
    ]
