# Generated by Django 3.1.4 on 2021-02-02 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0027_freigabe_lesen_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freigabe_Upload_Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freigabe_upload', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('ordner_rolle_firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner_rolle_firma')),
            ],
        ),
    ]
