# Generated by Django 3.1.4 on 2021-02-02 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0028_freigabe_upload_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordner_WFSch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner')),
                ('wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.workflow_schema')),
            ],
        ),
        migrations.CreateModel(
            name='Ordner_WFSch_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('ordner_wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner_wfsch')),
            ],
        ),
    ]
