# Generated by Django 3.1.4 on 2021-02-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0029_ordner_wfsch_ordner_wfsch_aktuell'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFSch_Stufe_Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.rolle')),
                ('wfsch_stufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.workflow_schema_stufe')),
            ],
        ),
        migrations.CreateModel(
            name='WFSch_Stufe_Rolle_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('wfsch_stufe_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wfsch_stufe_rolle')),
            ],
        ),
    ]
