# Generated by Django 3.1.4 on 2021-02-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0030_wfsch_stufe_rolle_wfsch_stufe_rolle_aktuell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projektstruktur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('projektstruktur_id', models.CharField(max_length=20)),
            ],
        ),
    ]
