# Generated by Django 3.1.4 on 2021-02-02 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0031_projektstruktur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolle_Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_id', models.CharField(max_length=20)),
                ('zeitstempel', models.DateTimeField()),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.rolle')),
            ],
        ),
    ]
