# Generated by Django 3.1.4 on 2021-02-02 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0032_rolle_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolle_Firma_Aktiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktiv', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('rolle_firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.rolle_firma')),
            ],
        ),
    ]
