# Generated by Django 3.1.4 on 2021-02-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0033_rolle_firma_aktiv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordner_Rolle_Firma_Aktuell',
            new_name='Ordner_Firma_Aktuell',
        ),
        migrations.CreateModel(
            name='Ordner_Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_id', models.CharField(max_length=20)),
                ('ordner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner')),
            ],
        ),
        migrations.AlterField(
            model_name='freigabe_lesen_firma',
            name='ordner_rolle_firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner_firma'),
        ),
        migrations.AlterField(
            model_name='freigabe_upload_firma',
            name='ordner_rolle_firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner_firma'),
        ),
        migrations.AlterField(
            model_name='ordner_firma_aktuell',
            name='ordner_rolle_firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner_firma'),
        ),
        migrations.DeleteModel(
            name='Ordner_Rolle_Firma',
        ),
    ]
