# Generated by Django 3.1.4 on 2021-02-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0034_auto_20210202_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordner_Firma_Aktuell',
        ),
    ]
