# Generated by Django 3.1.4 on 2021-02-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0035_delete_ordner_firma_aktuell'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordner_Freigabe_Lesen_Rolle',
            new_name='Freigabe_Lesen_Rolle',
        ),
        migrations.RenameModel(
            old_name='Ordner_Freigabe_Upload_Rolle',
            new_name='Freigabe_Upload_Rolle',
        ),
    ]
