# Generated by Django 3.1.4 on 2021-02-02 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0036_auto_20210202_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordner',
            name='bezeichnung',
        ),
        migrations.CreateModel(
            name='Ordner_Vorlage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_ordner_id', models.CharField(max_length=20)),
                ('ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner')),
            ],
        ),
        migrations.CreateModel(
            name='Ordner_Bezeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
                ('zeitstempel', models.DateTimeField()),
                ('ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner')),
            ],
        ),
    ]
