# Generated by Django 3.1.4 on 2021-02-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0037_auto_20210202_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordner',
            name='unterordner',
        ),
        migrations.CreateModel(
            name='Ordner_Unterordner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordner', to='projektadmin.ordner')),
                ('unterordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unterordner', to='projektadmin.ordner')),
            ],
        ),
    ]
