# Generated by Django 3.1.4 on 2021-02-03 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0038_auto_20210202_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='überordner_unterordner',
            name='unterordner',
        ),
        migrations.RemoveField(
            model_name='überordner_unterordner',
            name='überordner',
        ),
        migrations.AlterField(
            model_name='ordner_unterordner',
            name='ordner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_ordner', to='projektadmin.ordner'),
        ),
        migrations.AlterField(
            model_name='ordner_unterordner',
            name='unterordner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_unterordner', to='projektadmin.ordner'),
        ),
        migrations.DeleteModel(
            name='Ordner_Vorlage',
        ),
        migrations.DeleteModel(
            name='Überordner_Unterordner',
        ),
    ]
