# Generated by Django 3.1.4 on 2021-02-03 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0039_auto_20210203_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordner_Gelöscht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelöscht', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner')),
            ],
        ),
    ]
