# Generated by Django 3.1.4 on 2021-02-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0040_ordner_gelöscht'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordner',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
    ]
