# Generated by Django 3.1.4 on 2021-02-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0042_ordner_vorlage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordner_vorlage',
            name='zeitstempel',
        ),
        migrations.AddField(
            model_name='workflow_schema',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
    ]
