# Generated by Django 3.1.4 on 2021-02-03 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0043_auto_20210203_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFSCH_Bezeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
                ('zeitstempel', models.DateTimeField()),
                ('wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.workflow_schema')),
            ],
        ),
    ]
