# Generated by Django 3.1.4 on 2021-02-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0045_wfsch_gelöscht'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_schema',
            name='bezeichnung',
        ),
    ]
