# Generated by Django 3.1.4 on 2021-02-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0047_ordner_unterordner_aktuell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolle_Vorlage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_rolle_id', models.CharField(max_length=20)),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.rolle')),
            ],
        ),
    ]
