# Generated by Django 3.1.4 on 2021-02-09 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0048_rolle_vorlage'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Ordner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('ist_root_ordner', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='V_Ordner_Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_ordner')),
            ],
        ),
        migrations.CreateModel(
            name='V_Ordner_Unterordner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_ordner', to='projektadmin.v_ordner')),
                ('v_unterordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_unterordner', to='projektadmin.v_ordner')),
            ],
        ),
        migrations.CreateModel(
            name='V_Ordner_WFSch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_ordner')),
            ],
        ),
        migrations.CreateModel(
            name='V_PJS_Ordner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_ordner')),
            ],
        ),
        migrations.CreateModel(
            name='V_PJS_Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_zeitstempel', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='V_PJS_WFSch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='V_Projektstruktur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='V_Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='V_WFSch_Stufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='V_WFSch_Stufe_Folgestufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('v_wfsch_folgestufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_wfsch_folgestufe', to='projektadmin.v_wfsch_stufe')),
                ('v_wfsch_stufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_wfsch_stufe', to='projektadmin.v_wfsch_stufe')),
            ],
        ),
        migrations.CreateModel(
            name='V_WFSch_Stufe_Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('v_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_rolle')),
                ('v_wfsch_stufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_wfsch_stufe')),
            ],
        ),
        migrations.CreateModel(
            name='V_Workflow_Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='V_WFSch_Stufe_Rolle_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_wfsch_stufe_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_wfsch_stufe_rolle')),
            ],
        ),
        migrations.CreateModel(
            name='V_WFSch_Stufe_Gelöscht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelöscht', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_wfsch_stufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_wfsch_stufe')),
            ],
        ),
        migrations.CreateModel(
            name='V_WFSch_Stufe_Folgestufe_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_wfsch_stufe_folgestufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_wfsch_stufe_folgestufe')),
            ],
        ),
        migrations.CreateModel(
            name='V_WFSch_Stufe_Bezeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
                ('zeitstempel', models.DateTimeField()),
                ('v_wfsch_stufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_wfsch_stufe')),
            ],
        ),
        migrations.AddField(
            model_name='v_wfsch_stufe',
            name='v_wfsch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_workflow_schema'),
        ),
        migrations.CreateModel(
            name='V_WFSch_Gelöscht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelöscht', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_workflow_schema')),
            ],
        ),
        migrations.CreateModel(
            name='V_WFSch_Bezeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
                ('zeitstempel', models.DateTimeField()),
                ('v_wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_workflow_schema')),
            ],
        ),
        migrations.CreateModel(
            name='V_Rolle_Gelöscht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelöscht', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_rolle')),
            ],
        ),
        migrations.CreateModel(
            name='V_Rolle_Bezeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
                ('v_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_rolle')),
            ],
        ),
        migrations.CreateModel(
            name='V_Projektstruktur_Bezeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
                ('zeitstempel', models.DateTimeField()),
                ('projektstruktur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_projektstruktur')),
            ],
        ),
        migrations.CreateModel(
            name='V_PJS_WFSch_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_pjs_wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_pjs_wfsch')),
            ],
        ),
        migrations.AddField(
            model_name='v_pjs_wfsch',
            name='v_pjs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_projektstruktur'),
        ),
        migrations.AddField(
            model_name='v_pjs_wfsch',
            name='v_wfsch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_workflow_schema'),
        ),
        migrations.CreateModel(
            name='V_PJS_Rolle_Aktiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktiv', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_pjs_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_pjs_rolle')),
            ],
        ),
        migrations.AddField(
            model_name='v_pjs_rolle',
            name='v_pjs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_projektstruktur'),
        ),
        migrations.AddField(
            model_name='v_pjs_rolle',
            name='v_rolle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_rolle'),
        ),
        migrations.CreateModel(
            name='V_PJS_Ordner_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_pjs_ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_pjs_ordner')),
            ],
        ),
        migrations.AddField(
            model_name='v_pjs_ordner',
            name='v_pjs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_projektstruktur'),
        ),
        migrations.CreateModel(
            name='V_Ordner_WFSch_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner_wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_ordner_wfsch')),
            ],
        ),
        migrations.AddField(
            model_name='v_ordner_wfsch',
            name='v_wfsch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_workflow_schema'),
        ),
        migrations.CreateModel(
            name='V_Ordner_Unterordner_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner_unterordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_ordner_unterordner')),
            ],
        ),
        migrations.CreateModel(
            name='V_Ordner_Rolle_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_ordner_rolle')),
            ],
        ),
        migrations.AddField(
            model_name='v_ordner_rolle',
            name='v_rolle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_rolle'),
        ),
        migrations.CreateModel(
            name='V_Ordner_Gelöscht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelöscht', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_ordner')),
            ],
        ),
        migrations.CreateModel(
            name='V_Ordner_Freigabe_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freigabe_upload', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_ordner_rolle')),
            ],
        ),
        migrations.CreateModel(
            name='V_Ordner_Freigabe_Lesen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freigabe_lesen', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_ordner_rolle')),
            ],
        ),
        migrations.CreateModel(
            name='V_Ordner_Bezeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_ordner')),
            ],
        ),
    ]
