# Generated by Django 3.1.4 on 2021-02-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0049_auto_20210209_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='v_rolle_bezeichnung',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
    ]
