# Generated by Django 3.1.4 on 2021-02-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0050_v_rolle_bezeichnung_zeitstempel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolle_bezeichnung',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
    ]
