# Generated by Django 3.1.4 on 2021-02-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0051_rolle_bezeichnung_zeitstempel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='v_wfsch_stufe',
            name='v_wfsch',
        ),
    ]
