# Generated by Django 3.1.4 on 2021-02-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0052_remove_v_wfsch_stufe_v_wfsch'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFSch_Stufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='wfsch_stufe_firma',
            name='workflow_schema_stufe',
        ),
        migrations.AddField(
            model_name='wfsch_stufe_firma',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='wfsch_stufe_firma',
            name='wfsch_stufe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wfsch_stufe'),
        ),
        migrations.AlterField(
            model_name='wfsch_stufe_mitarbeiter',
            name='wfsch_stufe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wfsch_stufe'),
        ),
        migrations.AlterField(
            model_name='wfsch_stufe_rolle',
            name='wfsch_stufe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wfsch_stufe'),
        ),
        migrations.DeleteModel(
            name='Workflow_Schema_Stufe',
        ),
    ]
