# Generated by Django 3.1.4 on 2021-02-09 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0055_wfsch_stufe_bezeichnung'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFSch_Stufe_Folgestufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('wfsch_folgestufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfsch_folgestufe', to='projektadmin.wfsch_stufe')),
                ('wfsch_stufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfsch_stufe', to='projektadmin.wfsch_stufe')),
            ],
        ),
    ]
