# Generated by Django 3.1.4 on 2021-02-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0056_wfsch_stufe_folgestufe'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFSch_Stufe_Folgestufe_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('wfsch_stufe_folgestufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wfsch_stufe_folgestufe')),
            ],
        ),
    ]
