# Generated by Django 3.1.4 on 2021-02-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0057_wfsch_stufe_folgestufe_aktuell'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFSch_Vorlage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_wfsch_id', models.CharField(max_length=20)),
                ('wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.workflow_schema')),
            ],
        ),
        migrations.CreateModel(
            name='WFSch_Anfangsstufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('anfangsstufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wfsch_stufe')),
                ('wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.workflow_schema')),
            ],
        ),
    ]
