# Generated by Django 3.1.4 on 2021-02-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0058_wfsch_anfangsstufe_wfsch_vorlage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFSch_Stufe_Vorlage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_wfsch_stufe_id', models.CharField(max_length=20)),
                ('wfsch_stufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wfsch_stufe')),
            ],
        ),
        migrations.CreateModel(
            name='V_WFSch_Anfangsstufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('v_anfangsstufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_wfsch_stufe')),
                ('v_wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_workflow_schema')),
            ],
        ),
    ]
