# Generated by Django 3.1.4 on 2021-02-09 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0059_v_wfsch_anfangsstufe_wfsch_stufe_vorlage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfsch_stufe_firma',
            name='wfsch_stufe',
        ),
        migrations.AddField(
            model_name='wfsch_stufe_firma',
            name='wfsch_stufe_rolle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wfsch_stufe_rolle'),
        ),
        migrations.CreateModel(
            name='WFSch_Stufe_Firma_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('wfsch_stufe_firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wfsch_stufe_firma')),
            ],
        ),
    ]
