# Generated by Django 3.1.4 on 2021-02-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0060_auto_20210209_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projektstruktur',
            old_name='projektstruktur_id',
            new_name='v_pjs_id',
        ),
    ]
