# Generated by Django 3.1.4 on 2021-02-09 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0061_auto_20210209_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='v_ordner_wfsch_aktuell',
            name='v_ordner_wfsch',
        ),
        migrations.DeleteModel(
            name='Ordner_WFSch_Aktuell',
        ),
        migrations.DeleteModel(
            name='V_Ordner_WFSch_Aktuell',
        ),
    ]
