# Generated by Django 3.1.4 on 2021-02-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0062_auto_20210209_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WFSch_Stufe_Folgestufe_Aktuell',
        ),
    ]
