# Generated by Django 3.1.4 on 2021-02-11 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0063_delete_wfsch_stufe_folgestufe_aktuell'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFSch_Vorlage_Gelöscht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelöscht', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('wfsch_vorlage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wfsch_vorlage')),
            ],
        ),
    ]
