# Generated by Django 3.1.4 on 2021-02-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0064_wfsch_vorlage_gelöscht'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WFSch_Vorlage_Gelöscht',
        ),
    ]
