# Generated by Django 3.1.4 on 2021-02-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0065_delete_wfsch_vorlage_gelöscht'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfsch_vorlage',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
    ]
