# Generated by Django 3.1.4 on 2021-02-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0066_wfsch_vorlage_zeitstempel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfsch_stufe_vorlage',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
    ]
