# Generated by Django 3.1.4 on 2021-02-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0067_wfsch_stufe_vorlage_zeitstempel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rolle_Firma_Aktiv',
            new_name='Rolle_Firma_Aktuell',
        ),
        migrations.RenameField(
            model_name='rolle_firma_aktuell',
            old_name='aktiv',
            new_name='aktuell',
        ),
    ]
