# Generated by Django 3.1.4 on 2021-02-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0068_auto_20210211_2241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='V_PJS_Rolle_Aktiv',
            new_name='V_PJS_Rolle_Aktuell',
        ),
        migrations.RenameField(
            model_name='v_pjs_rolle_aktuell',
            old_name='aktiv',
            new_name='aktuell',
        ),
    ]
