# Generated by Django 3.1.4 on 2021-02-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0070_v_ordner_wfsch_aktuell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordner_WFSch_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('ordner_wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.ordner_wfsch')),
            ],
        ),
    ]
