# Generated by Django 3.1.4 on 2021-02-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0071_ordner_wfsch_aktuell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordner',
            name='workflow_schema',
        ),
    ]
