# Generated by Django 3.1.4 on 2021-02-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0072_remove_ordner_workflow_schema'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='V_Projektstruktur_Bezeichnung',
            new_name='V_PJS_Bezeichnung',
        ),
    ]
