# Generated by Django 3.1.4 on 2021-02-13 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0073_auto_20210213_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_PJS_Gelöscht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelöscht', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_pjs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.v_projektstruktur')),
            ],
        ),
    ]
