# Generated by Django 3.1.4 on 2021-02-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0074_v_pjs_gelöscht'),
    ]

    operations = [
        migrations.RenameField(
            model_name='v_pjs_bezeichnung',
            old_name='projektstruktur',
            new_name='v_pjs',
        ),
    ]
