# Generated by Django 3.1.4 on 2021-02-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0075_auto_20210213_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordner_firma',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
    ]
