# Generated by Django 3.1.4 on 2021-02-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0076_ordner_firma_zeitstempel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freigabe_lesen_firma',
            old_name='ordner_rolle_firma',
            new_name='ordner_firma',
        ),
        migrations.RenameField(
            model_name='freigabe_upload_firma',
            old_name='ordner_rolle_firma',
            new_name='ordner_firma',
        ),
    ]
