# Generated by Django 3.1.4 on 2021-02-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0078_rolle_mitarbeiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolle_Mitarbeiter_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('rolle_mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.rolle_mitarbeiter')),
            ],
        ),
    ]
