# Generated by Django 3.1.4 on 2021-02-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0079_rolle_mitarbeiter_aktuell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolle_mitarbeiter',
            name='rolle',
        ),
        migrations.AddField(
            model_name='rolle_mitarbeiter',
            name='rolle_firma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projektadmin.rolle_firma'),
        ),
    ]
