# Generated by Django 3.1.4 on 2021-02-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0080_auto_20210217_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfsch_stufe_mitarbeiter',
            name='gelöscht',
        ),
        migrations.RemoveField(
            model_name='wfsch_stufe_mitarbeiter',
            name='immer_erforderlich',
        ),
        migrations.RemoveField(
            model_name='wfsch_stufe_mitarbeiter',
            name='wfsch_stufe',
        ),
        migrations.AddField(
            model_name='wfsch_stufe_mitarbeiter',
            name='wfsch_stufe_firma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wfsch_stufe_firma'),
        ),
    ]
