# Generated by Django 3.1.4 on 2021-02-19 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0084_dokument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument_Bezeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
                ('zeitstempel', models.DateTimeField()),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.dokument')),
            ],
        ),
    ]
