# Generated by Django 3.1.4 on 2021-02-19 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0089_pfad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateiname', models.CharField(max_length=50)),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.dokument')),
                ('pfad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.pfad')),
            ],
        ),
    ]
