# Generated by Django 3.1.4 on 2021-02-19 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0090_datei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datei',
            name='dokument',
        ),
    ]
