# Generated by Django 3.1.4 on 2021-02-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0092_dokument_datei'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
    ]
