# Generated by Django 3.1.4 on 2021-02-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0094_kommentar_datei'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument_Ordner_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('dokument_ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.dokument_ordner')),
            ],
        ),
        migrations.CreateModel(
            name='Dokument_Kommentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.dokument')),
                ('kommentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.kommentar')),
            ],
        ),
    ]
