# Generated by Django 3.1.4 on 2021-02-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0095_dokument_kommentar_dokument_ordner_aktuell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dokument_Ordner_Aktuell',
        ),
    ]
