# Generated by Django 3.1.4 on 2021-02-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0096_delete_dokument_ordner_aktuell'),
    ]

    operations = [
        migrations.AddField(
            model_name='datei',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
    ]
