# Generated by Django 3.1.4 on 2021-02-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0098_kommentar_mitarbeiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kommentar',
            old_name='text',
            new_name='kommentartext',
        ),
    ]
