# Generated by Django 3.1.4 on 2021-02-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0099_auto_20210219_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokument',
            name='mitarbeiter',
        ),
        migrations.AddField(
            model_name='dokument',
            name='mitarbeiter_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
