# Generated by Django 3.1.4 on 2021-02-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0100_auto_20210221_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kommentar',
            name='mitarbeiter',
        ),
        migrations.AddField(
            model_name='kommentar',
            name='mitarbeiter_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
