# Generated by Django 3.1.4 on 2021-02-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0101_auto_20210221_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument_Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitarbeiter_id', models.CharField(max_length=20)),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
    ]
