# Generated by Django 3.1.4 on 2021-02-21 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0102_dokument_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument_download',
            name='dokument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projektadmin.dokument'),
        ),
    ]
