# Generated by Django 3.1.4 on 2021-02-22 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0103_dokument_download_dokument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.dokument')),
                ('wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.workflow_schema')),
            ],
        ),
    ]
