# Generated by Django 3.1.4 on 2021-02-22 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0105_wf_stufe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='zeitstempel',
        ),
        migrations.DeleteModel(
            name='WF_Stufe',
        ),
    ]
