# Generated by Django 3.1.4 on 2021-02-22 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0106_auto_20210222_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='WF_Stufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.workflow')),
            ],
        ),
    ]
