# Generated by Django 3.1.4 on 2021-02-22 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0107_wf_stufe'),
    ]

    operations = [
        migrations.CreateModel(
            name='WF_Stufe_Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.rolle')),
                ('wf_stufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wf_stufe')),
            ],
        ),
    ]
