# Generated by Django 3.1.4 on 2021-02-22 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0108_wf_stufe_rolle'),
    ]

    operations = [
        migrations.CreateModel(
            name='WF_Stufe_Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_id', models.CharField(max_length=20)),
                ('wf_stufe_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wf_stufe_rolle')),
            ],
        ),
    ]
