# Generated by Django 3.1.4 on 2021-02-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0110_wf_stufe_mitarbeiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='wf_stufe_mitarbeiter',
            name='immer_erforderlich',
            field=models.BooleanField(default=False),
        ),
    ]
