# Generated by Django 3.1.4 on 2021-02-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0111_wf_stufe_mitarbeiter_immer_erforderlich'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
            ],
        ),
    ]
