# Generated by Django 3.1.4 on 2021-02-22 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0112_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WF_Anfangsstufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfangsstufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wf_stufe')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.workflow')),
            ],
        ),
    ]
