# Generated by Django 3.1.4 on 2021-02-22 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0113_wf_anfangsstufe'),
    ]

    operations = [
        migrations.CreateModel(
            name='WF_Stufe_Folgestufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folgestufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folgestufe', to='projektadmin.wf_stufe')),
                ('stufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stufe', to='projektadmin.wf_stufe')),
            ],
        ),
        migrations.CreateModel(
            name='WF_Prüferstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeistempel', models.DateTimeField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.status')),
                ('wf_stufe_ma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.wf_stufe_mitarbeiter')),
            ],
        ),
    ]
