# Generated by Django 3.1.4 on 2021-02-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0114_wf_prüferstatus_wf_stufe_folgestufe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wf_stufe',
            name='workflow',
        ),
    ]
