# Generated by Django 3.1.4 on 2021-02-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0115_remove_wf_stufe_workflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wf_prüferstatus',
            old_name='zeistempel',
            new_name='zeitstempel',
        ),
    ]
