# Generated by Django 3.1.4 on 2021-02-22 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0116_auto_20210222_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument_Abgelehnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abgelehnt', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.dokument')),
            ],
        ),
    ]
