# Generated by Django 3.1.4 on 2021-02-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0117_dokument_abgelehnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='wf_stufe',
            name='bezeichnung',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
