# Generated by Django 3.1.4 on 2021-02-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0118_wf_stufe_bezeichnung'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='bezeichnung',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
