# Generated by Django 3.1.4 on 2021-02-23 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0119_workflow_bezeichnung'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wf_prüferstatus',
            old_name='wf_stufe_ma',
            new_name='wf_stufe_mitarbeiter',
        ),
    ]
