# Generated by Django 3.1.4 on 2021-02-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0120_auto_20210223_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datei_Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitarbeiter_id', models.CharField(max_length=20)),
                ('zeitstempel', models.DateTimeField()),
                ('datei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.datei')),
            ],
        ),
    ]
