# Generated by Django 3.1.4 on 2021-02-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0121_datei_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pfad_Projekte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfad', models.CharField(max_length=100)),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
    ]
