# Generated by Django 3.1.4 on 2021-02-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0122_pfad_projekte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pfad_Projekte',
            new_name='Pfad_Projekt',
        ),
    ]
