# Generated by Django 3.1.4 on 2021-03-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0123_auto_20210224_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datei',
            name='pfad',
        ),
    ]
