# Generated by Django 3.1.4 on 2021-03-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0124_remove_datei_pfad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pfad_Anhaenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfad', models.CharField(max_length=100)),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
    ]
