# Generated by Django 3.1.4 on 2021-03-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0125_pfad_anhaenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pfad_Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfad', models.CharField(max_length=100)),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
    ]
