# Generated by Django 3.1.4 on 2020-12-29 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projektadmin', '0008_auto_20201228_1622'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
                ('pfad', models.CharField(max_length=100)),
                ('zeitstempel', models.DateTimeField()),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ordner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projektadmin.ordner')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dokab.paket')),
            ],
        ),
    ]
