# Generated by Django 3.1.4 on 2020-12-29 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0008_auto_20201228_1622'),
        ('dokab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ist_abgeschlossen', models.BooleanField()),
                ('dokument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dokab.dokument')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dokab.status')),
                ('workflow_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.workflow_schema')),
            ],
        ),
    ]
