# Generated by Django 3.1.4 on 2020-12-29 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dokab', '0002_status_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitarbeiter_Stufe_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immer_erforderlich', models.BooleanField()),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dokab.status')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow_Stufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitarbeiter', models.ManyToManyField(through='dokab.Mitarbeiter_Stufe_Status', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokab.workflow')),
            ],
        ),
        migrations.AddField(
            model_name='mitarbeiter_stufe_status',
            name='workflow_stufe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokab.workflow_stufe'),
        ),
    ]
