# Generated by Django 3.1.4 on 2020-12-29 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dokab', '0003_auto_20201229_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ereignis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dokumentenhistorie_Eintrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('zeitstempel', models.DateTimeField()),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokab.dokument')),
                ('ereignis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dokab.ereignis')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
