# Generated by Django 3.1.4 on 2020-12-30 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0005_auto_20201230_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_stufe',
            name='vorstufe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dokab.workflow_stufe'),
        ),
    ]
