# Generated by Django 3.1.4 on 2020-12-30 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0006_workflow_stufe_vorstufe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='ist_abgeschlossen',
            new_name='abgeschlossen',
        ),
    ]
