# Generated by Django 3.1.4 on 2020-12-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0007_auto_20201230_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_stufe',
            name='abgeschlossen',
            field=models.BooleanField(default=False),
        ),
    ]
