# Generated by Django 3.1.4 on 2021-01-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0008_workflow_stufe_abgeschlossen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokument',
            name='paket',
        ),
        migrations.DeleteModel(
            name='Paket',
        ),
    ]
