# Generated by Django 3.1.4 on 2021-01-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0009_auto_20210122_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='abgeschlossen',
            new_name='aktuell',
        ),
    ]
