# Generated by Django 3.1.4 on 2021-01-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0010_auto_20210122_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='aktuell',
            new_name='abgeschlossen',
        ),
    ]
