# Generated by Django 3.1.4 on 2021-01-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0011_auto_20210122_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokument',
            name='mitarbeiter',
        ),
        migrations.AddField(
            model_name='dokument',
            name='mitarbeiter_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
