# Generated by Django 3.1.4 on 2021-01-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0012_auto_20210122_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumentenhistorie_eintrag',
            name='mitarbeiter',
        ),
        migrations.AddField(
            model_name='dokumentenhistorie_eintrag',
            name='mitarbeiter_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
