# Generated by Django 3.1.4 on 2021-01-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0013_auto_20210122_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow_stufe',
            old_name='abgeschlossen',
            new_name='aktuell',
        ),
        migrations.CreateModel(
            name='Datei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateiname', models.CharField(max_length=50)),
                ('pfad', models.CharField(max_length=100)),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dokab.dokument')),
            ],
        ),
    ]
