# Generated by Django 3.1.4 on 2021-01-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0014_auto_20210122_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_stufe',
            name='mitarbeiter',
        ),
    ]
