# Generated by Django 3.1.4 on 2021-01-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0016_firma_stufe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitarbeiter_stufe_status',
            name='mitarbeiter',
        ),
        migrations.AddField(
            model_name='mitarbeiter_stufe_status',
            name='mitarbeiter_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
