# Generated by Django 3.1.4 on 2021-01-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0017_auto_20210122_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter_stufe_status',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
    ]
