# Generated by Django 3.1.4 on 2021-01-30 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0018_mitarbeiter_stufe_status_aktiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='gelöscht',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='zeitstempel',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
