# Generated by Django 3.1.4 on 2021-01-30 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0019_auto_20210130_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_stufe',
            name='gelöscht',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow_stufe',
            name='zeitstempel',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
