# Generated by Django 3.1.4 on 2021-01-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0020_auto_20210130_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitarbeiter_stufe_status',
            name='aktiv',
        ),
    ]
