# Generated by Django 3.1.4 on 2021-01-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0024_auto_20210130_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitarbeiter_stufe_status',
            name='gelöscht',
        ),
        migrations.AddField(
            model_name='mitarbeiter_stufe_status',
            name='aktuell',
            field=models.BooleanField(default=True),
        ),
    ]
