# Generated by Django 3.1.4 on 2021-01-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0025_auto_20210131_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mitarbeiter_stufe_status',
            old_name='aktuell',
            new_name='gelöscht',
        ),
    ]
