# Generated by Django 3.1.4 on 2021-01-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0026_auto_20210131_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_stufe',
            name='gelöscht',
        ),
        migrations.RemoveField(
            model_name='workflow_stufe',
            name='zeitstempel',
        ),
    ]
