# Generated by Django 3.1.4 on 2021-01-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0027_auto_20210131_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_stufe',
            name='bezeichnung',
            field=models.CharField(default='Default', max_length=20),
        ),
    ]
