# Generated by Django 3.1.4 on 2021-01-31 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0028_workflow_stufe_bezeichnung'),
    ]

    operations = [
        migrations.CreateModel(
            name='WF_Update_Abgeschlossen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abgeschlossen', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokab.workflow')),
            ],
            options={
                'ordering': ['zeitstempel'],
            },
        ),
        migrations.DeleteModel(
            name='Firma_Stufe',
        ),
    ]
