# Generated by Django 3.1.4 on 2021-01-31 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0030_wf_update_gelöscht'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WF_Update_Gelöscht',
        ),
    ]
