# Generated by Django 3.1.4 on 2021-01-31 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0032_wf_stufe_update_aktuell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wf_stufe_update_aktuell',
            name='workflow',
        ),
        migrations.AddField(
            model_name='wf_stufe_update_aktuell',
            name='workflow_stufe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dokab.workflow_stufe'),
        ),
    ]
