# Generated by Django 3.1.4 on 2021-02-01 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0034_wf_update_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='gelöscht',
        ),
        migrations.RemoveField(
            model_name='status',
            name='zeitstempel',
        ),
        migrations.CreateModel(
            name='MA_Stufe_Status_Update_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('ma_stufe_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokab.mitarbeiter_stufe_status')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dokab.status')),
            ],
            options={
                'ordering': ['zeitstempel'],
            },
        ),
    ]
