# Generated by Django 3.1.4 on 2021-02-01 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0035_auto_20210201_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='abgeschlossen',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='gelöscht',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='zeitstempel',
        ),
    ]
