# Generated by Django 3.1.4 on 2021-02-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0036_auto_20210201_0154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WF_Update_Status',
        ),
    ]
