# Generated by Django 3.1.4 on 2021-02-01 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0037_delete_wf_update_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_stufe',
            name='aktuell',
        ),
    ]
