# Generated by Django 3.1.4 on 2021-02-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0038_remove_workflow_stufe_aktuell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitarbeiter_stufe_status',
            name='gelöscht',
        ),
        migrations.RemoveField(
            model_name='mitarbeiter_stufe_status',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mitarbeiter_stufe_status',
            name='zeitstempel',
        ),
    ]
