# Generated by Django 3.1.4 on 2021-02-01 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0039_auto_20210201_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anhang',
            name='dokumentenhistorie_eintrag',
        ),
        migrations.DeleteModel(
            name='Dokumentenhistorie_Eintrag',
        ),
        migrations.DeleteModel(
            name='Ereignis',
        ),
    ]
