# Generated by Django 3.1.4 on 2021-02-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0040_auto_20210201_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='freigegeben',
            field=models.BooleanField(default=False),
        ),
    ]
