# Generated by Django 3.1.4 on 2021-02-01 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0041_dokument_freigegeben'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statuskommentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('ma_stufe_status_update_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dokab.ma_stufe_status_update_status')),
            ],
        ),
    ]
