# Generated by Django 3.1.4 on 2021-02-22 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokab', '0042_statuskommentar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anhang',
        ),
        migrations.RemoveField(
            model_name='dokument',
            name='ordner',
        ),
        migrations.RemoveField(
            model_name='ma_stufe_status_update_status',
            name='ma_stufe_status',
        ),
        migrations.RemoveField(
            model_name='ma_stufe_status_update_status',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mitarbeiter_stufe_status',
            name='workflow_stufe',
        ),
        migrations.RemoveField(
            model_name='statuskommentar',
            name='ma_stufe_status_update_status',
        ),
        migrations.RemoveField(
            model_name='wf_stufe_update_aktuell',
            name='workflow_stufe',
        ),
        migrations.RemoveField(
            model_name='wf_update_abgeschlossen',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='dokument',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='workflow_schema',
        ),
        migrations.RemoveField(
            model_name='workflow_stufe',
            name='vorstufe',
        ),
        migrations.RemoveField(
            model_name='workflow_stufe',
            name='workflow',
        ),
        migrations.DeleteModel(
            name='Datei',
        ),
        migrations.DeleteModel(
            name='Dokument',
        ),
        migrations.DeleteModel(
            name='MA_Stufe_Status_Update_Status',
        ),
        migrations.DeleteModel(
            name='Mitarbeiter_Stufe_Status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Statuskommentar',
        ),
        migrations.DeleteModel(
            name='WF_Stufe_Update_Aktuell',
        ),
        migrations.DeleteModel(
            name='WF_Update_Abgeschlossen',
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
        migrations.DeleteModel(
            name='Workflow_Stufe',
        ),
    ]
