# Generated by Django 3.1.4 on 2021-02-24 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mängel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fälligkeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('fälligkeitsdatum', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mängel.ticket')),
            ],
        ),
    ]
