# Generated by Django 3.1.4 on 2021-02-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mängel', '0002_fälligkeit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fälligkeit',
            new_name='Ticket_Fälligkeit',
        ),
    ]
