# Generated by Django 3.1.4 on 2021-02-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mängel', '0004_ticket_bezeichnung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Kommentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitarbeiter_id', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=250)),
                ('zeitstempel', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mängel.ticket')),
            ],
        ),
    ]
