# Generated by Django 3.1.4 on 2021-02-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0121_datei_download'),
        ('mängel', '0006_ticket_empfängerfirma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Ausstellerstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.status')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mängel.ticket')),
            ],
        ),
    ]
