# Generated by Django 3.1.4 on 2021-02-24 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mängel', '0007_ticket_ausstellerstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Empfängerfirma_Gelesen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('ticket_empfängerfirma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mängel.ticket_empfängerfirma')),
            ],
        ),
    ]
