# Generated by Django 3.1.4 on 2021-02-24 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0121_datei_download'),
        ('mängel', '0009_ticket_empfängerfirma_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breite', models.FloatField()),
                ('hoehe', models.FloatField()),
                ('datei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.datei')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mängel.ticket')),
            ],
        ),
    ]
