# Generated by Django 3.1.4 on 2021-02-24 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mängel', '0011_ticket_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Plan_X',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_koordinate', models.FloatField()),
                ('zeitstempel', models.DateTimeField()),
                ('ticket_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mängel.ticket_plan')),
            ],
        ),
    ]
