# Generated by Django 3.1.4 on 2021-02-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mängel', '0013_ticket_plan_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pfad_Plaene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfad', models.CharField(max_length=100)),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Ticket_Fälligkeit',
            new_name='Ticket_Fälligkeitsdatum',
        ),
    ]
