# Generated by Django 3.1.4 on 2021-02-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mängel', '0014_auto_20210224_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Empfängerfirma_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('ticket_empfängerfirma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mängel.ticket_empfängerfirma')),
            ],
        ),
    ]
