# Generated by Django 3.1.4 on 2021-03-02 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mängel', '0015_ticket_empfängerfirma_aktuell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='ticket',
        ),
        migrations.CreateModel(
            name='Ticket_Gelöscht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelöscht', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mängel.ticket')),
            ],
        ),
    ]
