# Generated by Django 3.1.4 on 2021-03-03 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0124_remove_datei_pfad'),
        ('mängel', '0017_plan_bezeichnung_plan_gelöscht'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Kommentar_Anhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('datei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.datei')),
                ('ticket_kommentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mängel.ticket_kommentar')),
            ],
        ),
    ]
