# Generated by Django 3.1.4 on 2021-03-10 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projektadmin', '0125_pfad_anhaenge'),
        ('mängel', '0018_ticket_kommentar_anhang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Kommentar_Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektadmin.datei')),
                ('ticket_kommentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mängel.ticket_kommentar')),
            ],
        ),
    ]
