# Generated by Django 3.1.4 on 2021-03-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mängel', '0019_ticket_kommentar_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_kommentar_foto',
            name='breite_px',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket_kommentar_foto',
            name='hoehe_px',
            field=models.IntegerField(null=True),
        ),
    ]
