# Generated by Django 3.1.4 on 2021-02-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nachricht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verfasser', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=300)),
                ('betreff', models.CharField(max_length=50)),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
    ]
