# Generated by Django 3.1.4 on 2021-02-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kommunikation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nachricht',
            old_name='verfasser',
            new_name='verfasser_id',
        ),
        migrations.CreateModel(
            name='Nachricht_Empfänger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empfänger_id', models.CharField(max_length=20)),
                ('nachricht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kommunikation.nachricht')),
            ],
        ),
    ]
