# Generated by Django 3.1.4 on 2021-02-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kommunikation', '0002_auto_20210223_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nachricht_Empfänger_Gelesen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('nachricht_empfänger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kommunikation.nachricht_empfänger')),
            ],
        ),
    ]
