# Generated by Django 3.1.4 on 2020-12-13 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
                ('kurzbezeichnung', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Projekt_Mitarbeiter_Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ist_projektadmin', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.projekt')),
            ],
        ),
        migrations.CreateModel(
            name='Projekt_Firma_Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ist_projektadmin', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.firma')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.projekt')),
            ],
        ),
        migrations.AddField(
            model_name='projekt',
            name='firma',
            field=models.ManyToManyField(through='superadmin.Projekt_Firma_Mail', to='superadmin.Firma'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='mitarbeiter',
            field=models.ManyToManyField(through='superadmin.Projekt_Mitarbeiter_Mail', to=settings.AUTH_USER_MODEL),
        ),
    ]
