# Generated by Django 3.1.4 on 2021-01-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_auto_20201213_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='ist_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
