# Generated by Django 3.1.4 on 2021-01-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_mitarbeiter_ist_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='adresse',
        ),
        migrations.AddField(
            model_name='firma',
            name='hausnummer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='strasse',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
