# Generated by Django 3.1.4 on 2021-01-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_auto_20210113_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projekt',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='projekt_firma_mail',
            constraint=models.UniqueConstraint(fields=('projekt', 'firma'), name='verbindung_pj-fa_unique'),
        ),
        migrations.AddConstraint(
            model_name='projekt_mitarbeiter_mail',
            constraint=models.UniqueConstraint(fields=('projekt', 'mitarbeiter'), name='verbindung_pj-ma_unique'),
        ),
    ]
