# Generated by Django 3.1.4 on 2021-01-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_auto_20210114_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='postleitzahl',
            field=models.CharField(max_length=10),
        ),
    ]
