# Generated by Django 3.1.4 on 2021-02-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_auto_20210114_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='db_bezeichnung',
            field=models.CharField(default='pj_projektID', max_length=25),
        ),
    ]
