# Generated by Django 3.1.4 on 2021-02-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_projekt_db_bezeichnung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma_Gelöscht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelöscht', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.firma')),
            ],
        ),
    ]
