# Generated by Django 3.1.4 on 2021-02-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_firma_gelöscht'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
    ]
