# Generated by Django 3.1.4 on 2021-02-10 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_auto_20210210_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma_Kurzbezeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurzbezeichnung', models.CharField(max_length=50)),
                ('zeitstempel', models.DateTimeField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.firma')),
            ],
        ),
    ]
