# Generated by Django 3.1.4 on 2021-02-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_firma_kurzbezeichnung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='kurzbezeichnung',
        ),
    ]
