# Generated by Django 3.1.4 on 2021-02-10 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_remove_firma_kurzbezeichnung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma_Strasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strasse', models.CharField(max_length=50)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.firma')),
            ],
        ),
    ]
