# Generated by Django 3.1.4 on 2021-02-10 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_firma_strasse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='strasse',
        ),
        migrations.AddField(
            model_name='firma_strasse',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Firma_Hausnummer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hausnummer', models.CharField(max_length=10)),
                ('zeitstempel', models.DateTimeField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.firma')),
            ],
        ),
    ]
