# Generated by Django 3.1.4 on 2021-02-10 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0015_remove_firma_hausnummer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma_Postleitzahl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postleitzahl', models.CharField(max_length=15)),
                ('zeitstempel', models.DateTimeField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.firma')),
            ],
        ),
    ]
