# Generated by Django 3.1.4 on 2021-02-10 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0017_remove_firma_postleitzahl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='ort',
        ),
        migrations.CreateModel(
            name='Firma_Ort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ort', models.CharField(max_length=50)),
                ('zeitstempel', models.DateTimeField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.firma')),
            ],
        ),
    ]
