# Generated by Django 3.1.4 on 2021-02-10 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0018_auto_20210210_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='email',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='email_office',
        ),
        migrations.CreateModel(
            name='Firma_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.firma')),
            ],
        ),
    ]
