# Generated by Django 3.1.4 on 2021-02-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0019_auto_20210210_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='aktiv',
        ),
    ]
