# Generated by Django 3.1.4 on 2021-02-10 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0020_remove_firma_aktiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt_Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.firma')),
            ],
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='aktiv',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='bezeichnung',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='db_bezeichnung',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='kurzbezeichnung',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='mitarbeiter',
        ),
        migrations.AddField(
            model_name='projekt',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Projekt_Firma_Mail',
        ),
        migrations.AddField(
            model_name='projekt_firma',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.projekt'),
        ),
        migrations.AddConstraint(
            model_name='projekt_firma',
            constraint=models.UniqueConstraint(fields=('projekt', 'firma'), name='verbindung_pj-fa_unique'),
        ),
    ]
