# Generated by Django 3.1.4 on 2021-02-10 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0021_auto_20210210_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt_Bezeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=20)),
                ('zeitstempel', models.DateTimeField()),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.projekt')),
            ],
        ),
    ]
