# Generated by Django 3.1.4 on 2021-02-10 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0024_projekt_gelöscht'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt_Firma_Aktiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktiv', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('projekt_firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.projekt_firma')),
            ],
        ),
    ]
