# Generated by Django 3.1.4 on 2021-02-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0025_projekt_firma_aktiv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projekt_Firma_Aktiv',
            new_name='Projekt_Firma_Aktuell',
        ),
        migrations.RenameField(
            model_name='projekt_firma_aktuell',
            old_name='aktiv',
            new_name='aktuell',
        ),
    ]
