# Generated by Django 3.1.4 on 2021-02-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0027_projekt_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt_firma',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
    ]
