# Generated by Django 3.1.4 on 2021-02-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0029_mitarbeiter_gelöscht'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitarbeiter',
            name='aktiv',
        ),
    ]
