# Generated by Django 3.1.4 on 2021-02-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0031_mitarbeiter_ist_firmenadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitarbeiter',
            name='ist_firmenadmin',
        ),
    ]
