# Generated by Django 3.1.4 on 2021-02-11 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0032_remove_mitarbeiter_ist_firmenadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitarbeiter',
            name='ist_superadmin',
        ),
        migrations.CreateModel(
            name='Mitarbeiter_Ist_Superadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ist_superadmin', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
