# Generated by Django 3.1.4 on 2021-02-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0033_auto_20210211_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projekt_Mitarbeiter_Mail',
            new_name='Projekt_Mitarbeiter',
        ),
    ]
