# Generated by Django 3.1.4 on 2021-02-11 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0034_auto_20210211_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitarbeiter_Ist_Projektadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ist_projektadmin', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('projekt_mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.projekt_mitarbeiter')),
            ],
        ),
    ]
