# Generated by Django 3.1.4 on 2021-02-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0035_mitarbeiter_ist_projektadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projekt_mitarbeiter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='projekt_mitarbeiter',
            name='ist_projektadmin',
        ),
    ]
