# Generated by Django 3.1.4 on 2021-02-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0036_auto_20210211_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt_mitarbeiter',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
    ]
