# Generated by Django 3.1.4 on 2021-02-11 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0037_projekt_mitarbeiter_zeitstempel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt_Mitarbeiter_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('projekt_mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.projekt_mitarbeiter')),
            ],
        ),
    ]
