# Generated by Django 3.1.4 on 2021-02-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0038_projekt_mitarbeiter_aktuell'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
    ]
