# Generated by Django 3.1.4 on 2021-02-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0039_mitarbeiter_zeitstempel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firma_Email',
        ),
    ]
