# Generated by Django 3.1.4 on 2021-02-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0041_firma_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma_email',
            name='zeitstempel',
            field=models.DateTimeField(null=True),
        ),
    ]
