# Generated by Django 3.1.4 on 2021-02-11 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0042_firma_email_zeitstempel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma_Ist_Projektadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ist_projektadmin', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('projekt_firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.projekt_firma')),
            ],
        ),
    ]
