# Generated by Django 3.1.4 on 2021-02-11 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0043_firma_ist_projektadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projekt_mitarbeiter',
            name='projekt',
        ),
        migrations.AddField(
            model_name='projekt_mitarbeiter',
            name='projekt_firma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.projekt_firma'),
        ),
    ]
