# Generated by Django 3.1.4 on 2021-02-18 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0044_auto_20210212_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitarbeiter_ist_projektadmin',
            name='projekt_mitarbeiter',
        ),
        migrations.AddField(
            model_name='mitarbeiter_ist_projektadmin',
            name='firma_ist_projektadmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.firma_ist_projektadmin'),
        ),
    ]
