# Generated by Django 3.1.4 on 2021-02-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0045_auto_20210218_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projekt_mitarbeiter_aktuell',
            name='projekt_mitarbeiter',
        ),
        migrations.DeleteModel(
            name='Projekt_Mitarbeiter',
        ),
        migrations.DeleteModel(
            name='Projekt_Mitarbeiter_Aktuell',
        ),
    ]
