# Generated by Django 3.1.4 on 2021-02-01 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Order_Update_Unterordner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('v_unterordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_unterordner', to='vorlagen.v_ordner')),
                ('v_überordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_überordner', to='vorlagen.v_ordner')),
            ],
        ),
    ]
