# Generated by Django 3.1.4 on 2021-02-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0003_v_ordner_update_unterordner_aktuell'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Workflow_Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
    ]
