# Generated by Django 3.1.4 on 2021-02-01 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0004_v_workflow_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Ordner_Update_bezeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_ordner')),
            ],
        ),
    ]
