# Generated by Django 3.1.4 on 2021-02-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0005_v_ordner_update_bezeichnung'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='V_Ordner_Update_bezeichnung',
            new_name='V_Ordner_Bezeichnung',
        ),
    ]
