# Generated by Django 3.1.4 on 2021-02-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0006_auto_20210201_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
    ]
