# Generated by Django 3.1.4 on 2021-02-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0008_v_rolle_bezeichnung'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Ordner_Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_ordner')),
                ('v_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_rolle')),
            ],
        ),
    ]
