# Generated by Django 3.1.4 on 2021-02-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0010_v_ordner_freigabe_lesen'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Ordner_Freigabe_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freigabe_upload', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_ordner_rolle')),
            ],
        ),
    ]
