# Generated by Django 3.1.4 on 2021-02-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0011_v_ordner_freigabe_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='V_Order_Update_Unterordner',
            new_name='V_Ordner_Unterordner',
        ),
        migrations.RenameModel(
            old_name='V_Ordner_Update_Unterordner_aktuell',
            new_name='V_Ordner_Unterordner_aktuell',
        ),
    ]
