# Generated by Django 3.1.4 on 2021-02-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0012_auto_20210201_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='v_ordner_unterordner_aktuell',
            old_name='v_unterordner',
            new_name='v_ordner_unterordner',
        ),
    ]
