# Generated by Django 3.1.4 on 2021-02-01 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0013_auto_20210201_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Ordner_WFSch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_ordner')),
                ('v_wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_workflow_schema')),
            ],
        ),
    ]
