# Generated by Django 3.1.4 on 2021-02-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0015_v_ordner_wfsch_aktuell'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Ordner_Rolle_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_ordner_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_ordner_rolle')),
            ],
        ),
    ]
