# Generated by Django 3.1.4 on 2021-02-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0016_v_ordner_rolle_aktuell'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_WFSch_Stufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('v_wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_workflow_schema')),
            ],
        ),
        migrations.CreateModel(
            name='V_WFSch_Bezeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
                ('zeitstempel', models.DateTimeField()),
                ('v_wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_workflow_schema')),
            ],
        ),
    ]
