# Generated by Django 3.1.4 on 2021-02-01 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0018_v_wfsch_stufe_gelöscht'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_WFSch_Gelöscht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelöscht', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_workflow_schema')),
            ],
        ),
    ]
