# Generated by Django 3.1.4 on 2021-02-01 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0020_v_ordner_gelöscht'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Rolle_Gelöscht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelöscht', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_rolle')),
            ],
        ),
    ]
