# Generated by Django 3.1.4 on 2021-02-02 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0024_v_wfsch_stufe_folgestufe_aktuell'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_WFSch_Stufe_Rolle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('v_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_rolle')),
                ('v_wfsch_stufe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_wfsch_stufe')),
            ],
        ),
    ]
