# Generated by Django 3.1.4 on 2021-02-02 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0025_v_wfsch_stufe_rolle'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_WFSch_Stufe_Rolle_Aktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktuell', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_wfsch_stufe_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_wfsch_stufe_rolle')),
            ],
        ),
    ]
