# Generated by Django 3.1.4 on 2021-02-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0026_v_wfsch_stufe_rolle_aktuell'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_Projektstruktur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
            ],
        ),
    ]
