# Generated by Django 3.1.4 on 2021-02-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0029_v_pjs_ordner_aktuell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='v_pjs_ordner',
            old_name='v_projektstruktur',
            new_name='v_pjs',
        ),
    ]
