# Generated by Django 3.1.4 on 2021-02-02 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0030_auto_20210202_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='v_PJS_WFSch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitstempel', models.DateTimeField()),
                ('v_pjs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_projektstruktur')),
                ('v_wfsch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_workflow_schema')),
            ],
        ),
    ]
