# Generated by Django 3.1.4 on 2021-02-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0033_v_pjs_rolle'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_PJS_Rolle_Aktiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktiv', models.BooleanField()),
                ('zeitstempel', models.DateTimeField()),
                ('v_pjs_rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_pjs_rolle')),
            ],
        ),
    ]
