# Generated by Django 3.1.4 on 2021-02-02 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0034_v_pjs_rolle_aktiv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='v_ordner_unterordner',
            old_name='v_überordner',
            new_name='v_ordner',
        ),
        migrations.CreateModel(
            name='V_Projektstruktur_Bezeichnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50)),
                ('zeitstempel', models.DateTimeField()),
                ('projektstruktur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vorlagen.v_projektstruktur')),
            ],
        ),
    ]
