# Generated by Django 3.1.4 on 2021-02-09 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vorlagen', '0035_auto_20210202_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v_ordner_unterordner',
            name='v_ordner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v_ordner', to='vorlagen.v_ordner'),
        ),
    ]
